### ISSUE TITLE
error after install module

### ISSUE THREAD

**Issue by huynit** [feelinc/magento2-social-login#6]
hi.
after i install module, i try to login customer page and a get error 

> Fatal error: Uncaught Error: Call to a member function getExtensionAttributes() on null in C:\xampp\htdocs\magentostore\app\code\Sulaeman\SocialLogin\Observer\Customer\Model\ResourceModel\CustomerRepository\SaveAfterDataObject.php:56 Stack trace: #0 C:\xampp\htdocs\magentostore\vendor\magento\framework\Event\Invoker\InvokerDefault.php(72): Sulaeman\SocialLogin\Observer\Customer\Model\ResourceModel\CustomerRepository\SaveAfterDataObject->execute(Object(Magento\Framework\Event\Observer)) #1 C:\xampp\htdocs\magentostore\vendor\magento\framework\Event\Invoker\InvokerDefault.php(60): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Sulaeman\SocialLogin\Observer\Customer\Model\ResourceModel\CustomerRepository\SaveAfterDataObject), Object(Magento\Framework\Event\Observer)) #2 C:\xampp\htdocs\magentostore\vendor\magento\framework\Event\Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer)) #3 C:\xampp\htdocs\magentostore\generated\code\M in C:\xampp\htdocs\magentostore\app\code\Sulaeman\SocialLogin\Observer\Customer\Model\ResourceModel\CustomerRepository\SaveAfterDataObject.php on line 56

how can i fix this ?

**Comment by feelinc** [comment]
Hi sorry for the very late response.

I'm looking into this. If you have a fix, please make a pull request or let me know.

**Comment by huynit** [comment]
Hi feeling .
It's not error form your module.
But i need you support install modules. After  install modules my site
can't login

Vào 12 thg 2, 2018 17:10, "Sulaeman" <notifications@github.com> đã viết:

**Comment by feelinc** [comment]
This issue has been fixed with recent release, please check and try.
